config:
  EMR_CLUSTER_NAME: "Run-SpaRC"
  EMR_RELEASE: "emr-5.17.0"
  KEY_NAME: "wuda01"
  PATH_TO_KEY: "/home/wuda/"
  INSTANCE_TYPE: "r5.xlarge"
  CORE_COUNT: "2"
  BIG_PRICE: "0.2"
  MASTER_VOL: "32"
  CORE_VOL: "32"
  S3_BUCKET: "s3://wuda-notebook/logs"
  BOOTSTRAP: "file:///home/wuda/SpaRC/sparc-on-emr/src/emr-boostrap.sh"
  BOOTSTRAP_ARGS: "--notebook-dir,s3://wuda-notebook/jupyter_notebook"


